import { NextRequest, NextResponse } from "next/server";
import { promises as fs } from "fs";
import path from "path";
import type { Region } from "@/lib/types";

// ── Persistent insight storage ──
// Insights are generated once by CI (Monday 7 AM) or manually via CLI.
// The dashboard only reads saved insights — it never calls Claude directly.

const INSIGHTS_DIR = path.join(process.cwd(), "..", ".tmp", "insights");

function insightFilename(region: string, period: string, mode: string): string {
  const safePeriod = period.replace(/[^a-zA-Z0-9-]/g, "_");
  return `insights_${region}_${safePeriod}_${mode}.json`;
}

async function loadSavedInsight(region: string, period: string, mode: string): Promise<unknown | null> {
  const filename = insightFilename(region, period, mode);

  // Try Vercel Blob first (production)
  if (process.env.BLOB_READ_WRITE_TOKEN) {
    try {
      const { get } = await import("@vercel/blob");
      const result = await get(filename, { access: "private" });
      if (result && result.statusCode === 200) {
        const text = await new Response(result.stream).text();
        return JSON.parse(text);
      }
    } catch { /* not found, fall through */ }
  }

  // Try local file (development)
  try {
    const filepath = path.join(INSIGHTS_DIR, filename);
    const content = await fs.readFile(filepath, "utf-8");
    return JSON.parse(content);
  } catch {
    return null;
  }
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { region: regionStr, period, mode } = body as {
      region: string;
      period: string;
      period_type: "weekly" | "monthly";
      mode?: "default" | "report";
    };

    const region = regionStr.toUpperCase() as Region;
    if (region !== "EU" && region !== "UK") {
      return NextResponse.json({ error: "Invalid region" }, { status: 400 });
    }

    // Return permanently saved insight if it exists
    const modeKey = mode || "default";
    const saved = await loadSavedInsight(region, period, modeKey);
    if (saved) {
      return NextResponse.json(saved);
    }

    // No saved insight — insights are generated by CI or CLI, not live
    return NextResponse.json(
      { error: "Insights not yet generated for this period" },
      { status: 404 }
    );
  } catch (error) {
    console.error("Insights lookup failed:", error);
    return NextResponse.json(
      { error: "Failed to load insights" },
      { status: 500 }
    );
  }
}
